# Generated by Django 4.0.1 on 2022-01-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
    ]
